name: lithiumvision
channels:
  - conda-forge
  - pytorch # For PyTorch and CUDA toolkit
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy>=1.20.0
  - pandas>=1.3.0
  - matplotlib>=3.4.0
  - seaborn>=0.11.0
  - scikit-learn>=0.24.0
  - tqdm>=4.60.0
  - pytorch>=1.12.0 # Check MatterGen's PyTorch version compatibility
  - torchvision # Often a companion to PyTorch
  - torchaudio # Often a companion to PyTorch
  - cudatoolkit>=11.3  # Adjust to your CUDA version if using GPU; MatterGen might have specific needs
  - pymatgen>=2023.0.0 # Using a recent version
  - pyyaml>=6.0
  - scipy>=1.7.0
  - networkx>=2.6.0
  - plotly>=5.5.0
  - ipywidgets>=7.7.0 # For Jupyter widgets
  - jupyterlab>=3.0.0 # For JupyterLab environment
  - ipython>=8.0.0
  - pip:
    - mp-api>=0.30.1
    - hydra-core>=1.1.0 # A MatterGen dependency
    - e3nn>=0.5.0      # A MatterGen dependency
    - ase>=3.22.0      # For atomic simulation environment tasks
    # Add other pip packages if MatterGen or its dependencies require them
    # For MatterGen itself, it's typically installed via `pip install -e .` in its own directory