name: lithiumvision
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy>=1.20.0
  - pandas>=1.3.0
  - matplotlib>=3.4.0
  - seaborn>=0.11.0
  - scikit-learn>=0.24.0
  - tqdm>=4.60.0
  - pytorch>=1.12.0
  - cudatoolkit>=11.3  # 根据你的GPU支持选择适当版本
  - pymatgen>=2022.0.0
  - pyyaml>=6.0
  - scipy>=1.7.0
  - networkx>=2.6.0
  - plotly>=5.5.0
  - ipywidgets>=7.7.0
  - jupyter>=1.0.0
  - ipython>=8.0.0
  - pip:
    - mp-api>=0.30.1
    - hydra-core>=1.1.0
    - e3nn>=0.5.0
    - ase>=3.22.0 